# Generated by Django 4.0.4 on 2022-05-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
        ('offres', '0003_remove_offre_datedefin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('Matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Marque', models.CharField(max_length=50)),
                ('Modele', models.CharField(max_length=50)),
                ('TypePermis', models.CharField(max_length=1)),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offres.offre')),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkings.parking')),
            ],
        ),
    ]
