# Generated by Django 4.0.4 on 2022-06-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='Image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
