# Generated by Django 4.0.4 on 2022-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('IdTache', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
            ],
        ),
    ]
