# Generated by Django 4.0.4 on 2022-05-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taches', '0001_initial'),
        ('chauffeurs', '0001_initial'),
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voitures.voiture'),
        ),
        migrations.AddField(
            model_name='tache',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chauffeurs.chauffeur'),
        ),
    ]
