# Generated by Django 4.0.4 on 2022-05-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('cinA', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=13)),
                ('Pass', models.CharField(max_length=50)),
                ('Diplome', models.CharField(max_length=50)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
            ],
        ),
    ]
