# Generated by Django 4.0.4 on 2022-05-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('IdOffre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DateDebut', models.DateTimeField(auto_now_add=True)),
                ('DateDefin', models.DateTimeField(auto_now_add=True)),
                ('solde', models.FloatField(null=True)),
            ],
        ),
    ]
