# Generated by Django 4.0.4 on 2022-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='DateDebut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offre',
            name='DateDefin',
            field=models.DateTimeField(),
        ),
    ]
