# Generated by Django 4.0.4 on 2022-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_alter_offre_datedebut_alter_offre_datedefin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='DateDefin',
        ),
    ]
