# Generated by Django 4.0.4 on 2022-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cinCl', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=13)),
                ('TypePermis', models.CharField(max_length=1)),
                ('fidelite', models.BooleanField(default=False)),
            ],
        ),
    ]
