# Generated by Django 4.0.4 on 2022-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('Cin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Pass', models.CharField(max_length=50)),
            ],
        ),
    ]
