# Generated by Django 4.0.4 on 2022-05-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('Idparking', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('Emplacement', models.CharField(max_length=50)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agences.agence')),
            ],
        ),
    ]
